### ISSUE TITLE
SSL Handhsake

### ISSUE THREAD

**Issue by martiniturbide** [TeLLie/clipgrab-os2#1]
Hi 

I'm getting this error on the ported clipgrab. (Attached picture)
<img width="493" alt="ClipGrab" src="https://user-images.githubusercontent.com/498092/79060149-1bd9c400-7c47-11ea-83f2-c8c387529402.png">

Maybe I'm missing some libraries. I'm open for suggestions.

Regards

**Comment by Tellie** [comment]
Hi Martin,
It seems more peeps have this, and also from a other platform.
I will update it to latest version as soon we have the webkit for QT5

**Comment by Tellie** [comment]
As we have now a port with QT5 i believe it's fixed there so i  close this
